name: PR Check Links

on:
  pull_request:
    types: [ opened, edited, reopened, synchronize, ready_for_review ]

permissions:
  contents: read

jobs:
  check-pr-links:
    uses: metal3-io/project-infra/.github/workflows/pr-link-check.yml@f3c3ae367c63cada0274fc96ee6c0a1abd28fa97 # main
    with:
      upstream: https://github.com/metal3-io/cluster-api-provider-metal3.git
